version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: adtech_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    command: >
      sh -c "
      if [ ! -f artisan ]; then
        composer create-project laravel/laravel . && 
        chown -R www-data:www-data storage bootstrap/cache && 
        chmod -R 775 storage bootstrap/cache
      fi
      && php-fpm
      "

  web:
    image: nginx:alpine
    container_name: adtech_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: adtech_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adstech
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
